<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Meeting MOM</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">

    <div style="max-width: 700px; margin: auto; background: #ffffff; padding: 30px; border-radius: 10px;">

        <h1 style="margin-bottom: 10px;">
            Meeting Minutes
        </h1>

        <p style="color: #666;">
            Generated automatically by AI Meeting Assistant
        </p>

        <hr style="margin: 20px 0;">

        <h2>
            {{ $meeting->title }}
        </h2>

        <p>
            <strong>Date:</strong>
            {{ now()->format('M d, Y h:i A') }}
        </p>

        <hr style="margin: 20px 0;">

        <!-- SUMMARY -->

        <h3>
            Meeting Summary
        </h3>

        <p>
            {{ $meeting->summary }}
        </p>

        <hr style="margin: 20px 0;">

        <!-- ACTION ITEMS -->

        <h3>
            Action Items
        </h3>

        @php
            $actionItems = is_array($meeting->action_items)
                ? $meeting->action_items
                : json_decode($meeting->action_items, true);
        @endphp

        @foreach($actionItems as $item)

            <div style="margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-radius: 8px;">

                <p>
                    <strong>Owner:</strong>
                    {{ $item['owner'] ?? 'N/A' }}
                </p>

                <p>
                    <strong>Deadline:</strong>
                    {{ $item['deadline'] ?? 'Not specified' }}
                </p>

                <p>
                    <strong>Tasks:</strong>
                </p>

                <ul>

                    @foreach($item['tasks'] as $task)

                        <li>
                            {{ $task }}
                        </li>

                    @endforeach

                </ul>

            </div>

        @endforeach

        <hr style="margin: 20px 0;">

        <!-- FOOTER -->

        <p style="font-size: 13px; color: #888;">
            This email was automatically generated by the AI Meeting MOM Generator.
        </p>

    </div>

</body>
</html>